FROM golang:1.9

RUN go get -u github.com/pilu/fresh
RUN go get -u google.golang.org/api/calendar/v3
RUN go get -u golang.org/x/oauth2/
RUN go get -u cloud.google.com/go/compute/metadata
RUN go get -u github.com/joho/godotenv
RUN go get -u gopkg.in/mgo.v2
RUN go get -u github.com/satori/go.uuid
RUN go get -u github.com/rs/cors
RUN go get -u github.com/dustin/go-humanize
RUN go get github.com/grokify/html-strip-tags-go